# -*- coding: utf-8 -*-
"""tuto1q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CyEGXwtxTN4ojXHH0bN9wgFNw6PNIwV5
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

mydf=pd.read_csv('mall_customer.csv')
mydf.rename(columns={'Genre':'Gender'}, inplace=True)
mydf.sample(n=5)

sns.regplot(data = mydf, x = 'Annual_Income_(k$)', y = 'Spending_Score');
