# -*- coding: utf-8 -*-
"""tuto1q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CyEGXwtxTN4ojXHH0bN9wgFNw6PNIwV5
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

mydf=pd.read_csv('mall_customer.csv')
mydf.rename(columns={'Genre':'Gender'}, inplace=True)
mydf.sample(n=5)

"""!pip install sweetviz"""

"""# importing sweetviz library
import sweetviz as sv

#analyzing the dataset
advert_report = sv.analyze(mydf)

#display the report
advert_report.show_html('Advertising.html')"""

"""advert_report.show_notebook()"""

sns.regplot(data = mydf, x = 'Annual_Income_(k$)', y = 'Spending_Score');

corr = mydf.corr(method = 'pearson')
corr

plt.figure(figsize=(10,8), dpi =500)
sns.heatmap(corr,annot=True,fmt=".2f", linewidth=.5)
plt.show()
